### ISSUE TITLE
Ajax Importer doesn't import everything

### ISSUE THREAD

**Issue by xmovu** [inkloud/life365-prestashop-module#6]
Hey there,

It looks like the Ajax Importer, both via Web or CURL doesn't import everything, though if I click in the backend in import products, it does.

Somehow, the ajax importer only imports around 191 products. And all are selected with the corresponding categories.

This is what it syncs, as it doesn't even sync the whole catalog:

`"Section: 1<br />"
"CATEGORY 1: IMPORT offset 0<br />"
"Set quantity product 2507  KX-FA136X 1606222618"
"Skip product 2507 latest version already"
"Set quantity product 5564  KYOTK865C 1594319811"
"Skip product 5564 latest version already"
"Set quantity product 5488  XERP8E 1595613844"
"Skip product 5488 latest version already"
"Set quantity product 9156 AD50W80-4 1634120651"
"Skip product 9156 latest version already"
"Set quantity product 9158 AD50W80-8 1600174298"
"Skip product 9158 latest version already"
"Set quantity product 7597 AGCACP13 1662465410"
"Skip product 7597 latest version already"
"Set quantity product 7598 AGCACP16 1665510602"
"Skip product 7598 latest version already"
"Set quantity product 7602 AGCAEP102 1607511016"
"Skip product 7602 latest version already"
"Set quantity product 9930 AGCAEP102BR 1652466559"
"Skip product 9930 latest version already"
"Set quantity product 14154 AGCOSP40BK 1665510394"
"Skip product 14154 latest version already"
"Set quantity product 9527 AGCZIR91B 1665510439"
"Skip product 9527 latest version already"
"Set quantity product 7908 AGEPERC05B 1652269864"
"Skip product 7908 latest version already"
"Set quantity product 9528 AGEPERC09B 1665667078"
"Skip product 9528 latest version already"
"Set quantity product 14210 AGEPERC23BK 1665510744"
"Skip product 14210 latest version already"
"Set quantity product 8418 AGEPERC23BR 1665510803"
"Skip product 8418 latest version already"
"Set quantity product 9529 AGEPERC27B 1607512675"
"Skip product 9529 latest version already"
"Set quantity product 7594 AGEPERC30 1663675716"
"Skip product 7594 latest version already"
"Set quantity product 7909 AGEPERC31B 1665510910"
"Skip product 7909 latest version already"
"Set quantity product 7910 AGEPERC32B 1617642659"
"Skip product 7910 latest version already"
"Set quantity product 7981 AGEPERC38BR 1665510089"
"Skip product 7981 latest version already"
"Set quantity product 10363 AGEPFX2190 1599760137"
"Skip product 10363 latest version already"
"Set quantity product 7911 AGEPFX890 1613405674"
"Skip product 7911 latest version already"
"Set quantity product 13780 AGEPLQ20 1599760189"
"Skip product 13780 latest version already"
"Set quantity product 8244 AGEPLQ2070 1599760222"
"Skip product 8244 latest version already"
"Set quantity product 8245 AGEPLQ3000 1622034446"
"Skip product 8245 latest version already"
"Set quantity product 8243 AGEPLQ680 1599760276"
"Skip product 8243 latest version already"
"Set quantity product 12115 AGEPLQ690 1599760329"
"Skip product 12115 latest version already"
"Set quantity product 7599 AGEPLQ800 1662394472"
"Skip product 7599 latest version already"
"Set quantity product 10626 AGEPLX350 1661173718"
"Skip product 10626 latest version already"
"Set quantity product 14818 AGEPMX100 1599760437"
"Skip product 14818 latest version already"
"Set quantity product 7600 AGLE2380 1638192457"
"Skip product 7600 latest version already"
"Set quantity product 18320 AGOK5320 1658407177"
"Skip product 18320 latest version already"
"Set quantity product 14650 AGOKI1120 1600866859"
"Skip product 14650 latest version already"
"Set quantity product 9504 AGOKI5100 1599760598"
"Skip product 9504 latest version already"
"Set quantity product 8195 AGOKI5520 1599760657"
"Skip product 8195 latest version already"
"Set quantity product 7595 AGOKIML182 1627303365"
"Skip product 7595 latest version already"
"Set quantity product 7593 AGOLPR2 1661790717"
"Skip product 7593 latest version already"
"Set quantity product 7912 AGOLPR4 1599760811"
"Skip product 7912 latest version already"
"Set quantity product 7601 AGOLPR50 1621425695"
"Skip product 7601 latest version already"
"Set quantity product 9530 AGPRP300B 1599760871"
"Skip product 9530 latest version already"
"Set quantity product 13961 AGRC700BK 1635178879"
"Skip product 13961 latest version already"
"Set quantity product 7913 AGSP200B 1652100601"
"Skip product 7913 latest version already"
"Set quantity product 13781 AGSP300BK 1599760933"
"Skip product 13781 latest version already"
"Set quantity product 14968 AGTAT2440 1599760953"
"Skip product 14968 latest version already"
"Set quantity product 17420 ARCAGI50C 1657204996"`

Can you help?

**Comment by giancarlospadini** [comment]
The bug is:
Fatal error: Uncaught PrestaShopBundle\Exception\NotImplementedException: Shop context types other than "single shop" are not supported in /home/***/domains/***.pt/public_html/src/PrestaShopBundle/Entity/Repository/StockManagementRepository.php:142 Stack trace: #0 /home/***/domains/***.pt/public_html/src/PrestaShopBundle/Entity/Repository/StockMovementRepository.php(58): PrestaShopBundle\Entity\Repository\StockManagementRepository->__construct(Object(ContainerTq1dggx\appProdProjectContainer), Object(Doctrine\DBAL\Connection), Object(Doctrine\ORM\EntityManager), Object(PrestaShop\PrestaShop\Adapter\LegacyContext), Object(PrestaShop\PrestaShop\Adapter\ImageManager), 'ps_') #1 /home/***/domains/***.pt/public_html/var/cache/dev/ContainerTq1dggx/getPrestashop_Core_Api_StockMovement_RepositoryService.php(8): PrestaShopBundle\Entity\Repository\StockMovementRepository->__construct(Object(ContainerTq1dggx\appProdProjectContainer), Object(Doctrine\DBAL\Connection), Object(Doctrine\ORM\EntityManager), Object(PrestaShop\P in /home/***/domains/***.pt/public_html/src/PrestaShopBundle/Entity/Repository/StockManagementRepository.php on line 142

**Comment by xmovu** [comment]
Thank you @giancarlospadini !

**Comment by giancarlospadini** [comment]
This bug is fixed on version 1.2.90
